-- AlterTable
ALTER TABLE `aula` ADD COLUMN `Titulo` VARCHAR(191) NOT NULL DEFAULT 'Aula exemplo';

-- AlterTable
ALTER TABLE `pessoa` ADD COLUMN `Discord` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `Github` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `Instagram` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `Linkedin` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `Twitter` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `Youtube` VARCHAR(191) NULL DEFAULT '';
